# Run docker-compose build
# Run docker-compose up
# Live long and prosper

version: '3.1'

services:

  microservice-1:
    container_name: currencyexchange 
    image: mooneshkachroo/aws-currency-exchange-service-h2:0.0.1-SNAPSHOT
    ports:
      - "8000:8000"

  microservice-2:
    container_name: currency_conversion
    image: mooneshkachroo/aws-currency-conversion-service:0.0.1-SNAPSHOT
    environment:
      CURRENCY_EXCHANGE_URI: http://currencyexchange:8000 
    ports:
      - "8100:8100"